generator:
  class: sfDoctrineGenerator
  param:
    model_class:           StructureContact
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          structure_contact
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:         Liste des contacts (structures)
        display: [Nom, prenom, fonction]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
