<?php

/**
 * BaseAnnonceCompetence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $annonce_id
 * @property integer $competence_id
 * @property Annonce $Annonce
 * @property Competence $Competence
 * 
 * @method integer           getId()            Returns the current record's "id" value
 * @method integer           getAnnonceId()     Returns the current record's "annonce_id" value
 * @method integer           getCompetenceId()  Returns the current record's "competence_id" value
 * @method Annonce           getAnnonce()       Returns the current record's "Annonce" value
 * @method Competence        getCompetence()    Returns the current record's "Competence" value
 * @method AnnonceCompetence setId()            Sets the current record's "id" value
 * @method AnnonceCompetence setAnnonceId()     Sets the current record's "annonce_id" value
 * @method AnnonceCompetence setCompetenceId()  Sets the current record's "competence_id" value
 * @method AnnonceCompetence setAnnonce()       Sets the current record's "Annonce" value
 * @method AnnonceCompetence setCompetence()    Sets the current record's "Competence" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnnonceCompetence extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('annonce_competence');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('annonce_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('competence_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Annonce', array(
             'local' => 'annonce_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Competence', array(
             'local' => 'competence_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}