<?php

/**
 * BaseProfilCompetence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $profil_id
 * @property integer $competence_id
 * @property Profil $Profil
 * @property Competence $Competence
 * 
 * @method integer          getId()            Returns the current record's "id" value
 * @method integer          getProfilId()      Returns the current record's "profil_id" value
 * @method integer          getCompetenceId()  Returns the current record's "competence_id" value
 * @method Profil           getProfil()        Returns the current record's "Profil" value
 * @method Competence       getCompetence()    Returns the current record's "Competence" value
 * @method ProfilCompetence setId()            Sets the current record's "id" value
 * @method ProfilCompetence setProfilId()      Sets the current record's "profil_id" value
 * @method ProfilCompetence setCompetenceId()  Sets the current record's "competence_id" value
 * @method ProfilCompetence setProfil()        Sets the current record's "Profil" value
 * @method ProfilCompetence setCompetence()    Sets the current record's "Competence" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfilCompetence extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profil_competence');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('profil_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('competence_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profil', array(
             'local' => 'profil_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Competence', array(
             'local' => 'competence_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}