<?php

/**
 * BaseEventAdmin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $event_id
 * @property integer $profil_id
 * @property Event $Event
 * @property Profil $Profil
 * 
 * @method integer    getId()        Returns the current record's "id" value
 * @method integer    getEventId()   Returns the current record's "event_id" value
 * @method integer    getProfilId()  Returns the current record's "profil_id" value
 * @method Event      getEvent()     Returns the current record's "Event" value
 * @method Profil     getProfil()    Returns the current record's "Profil" value
 * @method EventAdmin setId()        Sets the current record's "id" value
 * @method EventAdmin setEventId()   Sets the current record's "event_id" value
 * @method EventAdmin setProfilId()  Sets the current record's "profil_id" value
 * @method EventAdmin setEvent()     Sets the current record's "Event" value
 * @method EventAdmin setProfil()    Sets the current record's "Profil" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventAdmin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_admin');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('profil_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Profil', array(
             'local' => 'profil_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}