<?php

/**
 * BaseMessagerie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $profil_id
 * @property integer $sender_id
 * @property string $sujet
 * @property clob $message
 * @property timestamp $seen_at
 * @property boolean $is_sent
 * @property boolean $is_deleted_sender
 * @property boolean $is_deleted_receiver
 * @property Profil $Profil
 * @property Profil $Sender
 * 
 * @method integer    getId()                  Returns the current record's "id" value
 * @method integer    getProfilId()            Returns the current record's "profil_id" value
 * @method integer    getSenderId()            Returns the current record's "sender_id" value
 * @method string     getSujet()               Returns the current record's "sujet" value
 * @method clob       getMessage()             Returns the current record's "message" value
 * @method timestamp  getSeenAt()              Returns the current record's "seen_at" value
 * @method boolean    getIsSent()              Returns the current record's "is_sent" value
 * @method boolean    getIsDeletedSender()     Returns the current record's "is_deleted_sender" value
 * @method boolean    getIsDeletedReceiver()   Returns the current record's "is_deleted_receiver" value
 * @method Profil     getProfil()              Returns the current record's "Profil" value
 * @method Profil     getSender()              Returns the current record's "Sender" value
 * @method Messagerie setId()                  Sets the current record's "id" value
 * @method Messagerie setProfilId()            Sets the current record's "profil_id" value
 * @method Messagerie setSenderId()            Sets the current record's "sender_id" value
 * @method Messagerie setSujet()               Sets the current record's "sujet" value
 * @method Messagerie setMessage()             Sets the current record's "message" value
 * @method Messagerie setSeenAt()              Sets the current record's "seen_at" value
 * @method Messagerie setIsSent()              Sets the current record's "is_sent" value
 * @method Messagerie setIsDeletedSender()     Sets the current record's "is_deleted_sender" value
 * @method Messagerie setIsDeletedReceiver()   Sets the current record's "is_deleted_receiver" value
 * @method Messagerie setProfil()              Sets the current record's "Profil" value
 * @method Messagerie setSender()              Sets the current record's "Sender" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessagerie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('messagerie');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('profil_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sender_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sujet', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('message', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('seen_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('is_sent', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('is_deleted_sender', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('is_deleted_receiver', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('is_deleted', array(
             'fields' => 
             array(
              0 => 'is_deleted_sender',
             ),
             ));
        $this->index('is_deleted2', array(
             'fields' => 
             array(
              0 => 'is_deleted_receiver',
             ),
             ));
        $this->index('is_sent', array(
             'fields' => 
             array(
              0 => 'is_sent',
             ),
             ));
        $this->index('created_at', array(
             'fields' => 
             array(
              0 => 'created_at',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profil', array(
             'local' => 'profil_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Profil as Sender', array(
             'local' => 'sender_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}