<?php

/**
 * BaseExpertise
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property clob $description
 * @property Doctrine_Collection $Profil
 * @property Doctrine_Collection $ProfilExpertise
 * 
 * @method string              getNom()             Returns the current record's "nom" value
 * @method clob                getDescription()     Returns the current record's "description" value
 * @method Doctrine_Collection getProfil()          Returns the current record's "Profil" collection
 * @method Doctrine_Collection getProfilExpertise() Returns the current record's "ProfilExpertise" collection
 * @method Expertise           setNom()             Sets the current record's "nom" value
 * @method Expertise           setDescription()     Sets the current record's "description" value
 * @method Expertise           setProfil()          Sets the current record's "Profil" collection
 * @method Expertise           setProfilExpertise() Sets the current record's "ProfilExpertise" collection
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExpertise extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('expertise');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Profil', array(
             'refClass' => 'ProfilExpertise',
             'local' => 'expertise_id',
             'foreign' => 'profil_id'));

        $this->hasMany('ProfilExpertise', array(
             'local' => 'id',
             'foreign' => 'expertise_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nom',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}