<?php

/**
 * BaseEventMetier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $event_id
 * @property integer $metier_id
 * @property Event $Event
 * @property Metier $Metier
 * 
 * @method integer     getId()        Returns the current record's "id" value
 * @method integer     getEventId()   Returns the current record's "event_id" value
 * @method integer     getMetierId()  Returns the current record's "metier_id" value
 * @method Event       getEvent()     Returns the current record's "Event" value
 * @method Metier      getMetier()    Returns the current record's "Metier" value
 * @method EventMetier setId()        Sets the current record's "id" value
 * @method EventMetier setEventId()   Sets the current record's "event_id" value
 * @method EventMetier setMetierId()  Sets the current record's "metier_id" value
 * @method EventMetier setEvent()     Sets the current record's "Event" value
 * @method EventMetier setMetier()    Sets the current record's "Metier" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventMetier extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_metier');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('metier_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Metier', array(
             'local' => 'metier_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}