<?php

/**
 * BaseStructureCompetence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $structure_id
 * @property integer $competence_id
 * @property Structure $Structure
 * @property Competence $Competence
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getStructureId()   Returns the current record's "structure_id" value
 * @method integer             getCompetenceId()  Returns the current record's "competence_id" value
 * @method Structure           getStructure()     Returns the current record's "Structure" value
 * @method Competence          getCompetence()    Returns the current record's "Competence" value
 * @method StructureCompetence setId()            Sets the current record's "id" value
 * @method StructureCompetence setStructureId()   Sets the current record's "structure_id" value
 * @method StructureCompetence setCompetenceId()  Sets the current record's "competence_id" value
 * @method StructureCompetence setStructure()     Sets the current record's "Structure" value
 * @method StructureCompetence setCompetence()    Sets the current record's "Competence" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStructureCompetence extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('structure_competence');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('structure_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('competence_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Structure', array(
             'local' => 'structure_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Competence', array(
             'local' => 'competence_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}