<?php

/**
 * BaseFiliere
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property clob $description
 * @property boolean $is_activated
 * @property Doctrine_Collection $Profil
 * @property Doctrine_Collection $Mailing
 * @property Doctrine_Collection $MailingFiliere
 * @property Doctrine_Collection $ProfilFiliere
 * @property Doctrine_Collection $Ressource
 * @property Doctrine_Collection $RessourceFiliere
 * @property Doctrine_Collection $Event
 * @property Doctrine_Collection $EventFiliere
 * @property Doctrine_Collection $Structure
 * @property Doctrine_Collection $StructureFiliere
 * @property Doctrine_Collection $Projet
 * @property Doctrine_Collection $ProjetFiliere
 * 
 * @method string              getNom()              Returns the current record's "nom" value
 * @method clob                getDescription()      Returns the current record's "description" value
 * @method boolean             getIsActivated()      Returns the current record's "is_activated" value
 * @method Doctrine_Collection getProfil()           Returns the current record's "Profil" collection
 * @method Doctrine_Collection getMailing()          Returns the current record's "Mailing" collection
 * @method Doctrine_Collection getMailingFiliere()   Returns the current record's "MailingFiliere" collection
 * @method Doctrine_Collection getProfilFiliere()    Returns the current record's "ProfilFiliere" collection
 * @method Doctrine_Collection getRessource()        Returns the current record's "Ressource" collection
 * @method Doctrine_Collection getRessourceFiliere() Returns the current record's "RessourceFiliere" collection
 * @method Doctrine_Collection getEvent()            Returns the current record's "Event" collection
 * @method Doctrine_Collection getEventFiliere()     Returns the current record's "EventFiliere" collection
 * @method Doctrine_Collection getStructure()        Returns the current record's "Structure" collection
 * @method Doctrine_Collection getStructureFiliere() Returns the current record's "StructureFiliere" collection
 * @method Doctrine_Collection getProjet()           Returns the current record's "Projet" collection
 * @method Doctrine_Collection getProjetFiliere()    Returns the current record's "ProjetFiliere" collection
 * @method Filiere             setNom()              Sets the current record's "nom" value
 * @method Filiere             setDescription()      Sets the current record's "description" value
 * @method Filiere             setIsActivated()      Sets the current record's "is_activated" value
 * @method Filiere             setProfil()           Sets the current record's "Profil" collection
 * @method Filiere             setMailing()          Sets the current record's "Mailing" collection
 * @method Filiere             setMailingFiliere()   Sets the current record's "MailingFiliere" collection
 * @method Filiere             setProfilFiliere()    Sets the current record's "ProfilFiliere" collection
 * @method Filiere             setRessource()        Sets the current record's "Ressource" collection
 * @method Filiere             setRessourceFiliere() Sets the current record's "RessourceFiliere" collection
 * @method Filiere             setEvent()            Sets the current record's "Event" collection
 * @method Filiere             setEventFiliere()     Sets the current record's "EventFiliere" collection
 * @method Filiere             setStructure()        Sets the current record's "Structure" collection
 * @method Filiere             setStructureFiliere() Sets the current record's "StructureFiliere" collection
 * @method Filiere             setProjet()           Sets the current record's "Projet" collection
 * @method Filiere             setProjetFiliere()    Sets the current record's "ProjetFiliere" collection
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFiliere extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('filiere');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('is_activated', array(
             'fields' => 
             array(
              0 => 'is_activated',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Profil', array(
             'refClass' => 'ProfilFiliere',
             'local' => 'filiere_id',
             'foreign' => 'profil_id'));

        $this->hasMany('Mailing', array(
             'refClass' => 'MailingFiliere',
             'local' => 'filiere_id',
             'foreign' => 'mailing_id'));

        $this->hasMany('MailingFiliere', array(
             'local' => 'id',
             'foreign' => 'filiere_id'));

        $this->hasMany('ProfilFiliere', array(
             'local' => 'id',
             'foreign' => 'filiere_id'));

        $this->hasMany('Ressource', array(
             'refClass' => 'RessourceFiliere',
             'local' => 'filiere_id',
             'foreign' => 'ressource_id'));

        $this->hasMany('RessourceFiliere', array(
             'local' => 'id',
             'foreign' => 'filiere_id'));

        $this->hasMany('Event', array(
             'refClass' => 'EventFiliere',
             'local' => 'filiere_id',
             'foreign' => 'event_id'));

        $this->hasMany('EventFiliere', array(
             'local' => 'id',
             'foreign' => 'filiere_id'));

        $this->hasMany('Structure', array(
             'refClass' => 'StructureFiliere',
             'local' => 'filiere_id',
             'foreign' => 'structure_id'));

        $this->hasMany('StructureFiliere', array(
             'local' => 'id',
             'foreign' => 'filiere_id'));

        $this->hasMany('Projet', array(
             'refClass' => 'ProjetFiliere',
             'local' => 'filiere_id',
             'foreign' => 'projet_id'));

        $this->hasMany('ProjetFiliere', array(
             'local' => 'id',
             'foreign' => 'filiere_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nom',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}