<?php

/**
 * BaseStructure
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $createur_id
 * @property string $nom
 * @property string $adresse
 * @property string $adresse2
 * @property string $ville
 * @property string $code_postal
 * @property string $code_insee
 * @property string $tel
 * @property string $mail
 * @property string $photo
 * @property string $photo_crop
 * @property clob $presentation
 * @property clob $missions
 * @property clob $but
 * @property clob $strategie
 * @property string $url
 * @property Profil $Profil
 * @property Doctrine_Collection $Metier
 * @property Doctrine_Collection $Theme
 * @property Doctrine_Collection $Competence
 * @property Doctrine_Collection $Filiere
 * @property Doctrine_Collection $ProfilStructure
 * @property Doctrine_Collection $Event
 * @property Doctrine_Collection $EventStructure
 * @property Doctrine_Collection $StructureTheme
 * @property Doctrine_Collection $StructureFiliere
 * @property Doctrine_Collection $StructureCompetence
 * @property Doctrine_Collection $StructureMetier
 * @property Doctrine_Collection $StructureContact
 * @property Doctrine_Collection $Projet
 * @property Doctrine_Collection $ProjetStructure
 * @property Doctrine_Collection $ProjetStructurePartenaire
 * 
 * @method integer             getCreateurId()                Returns the current record's "createur_id" value
 * @method string              getNom()                       Returns the current record's "nom" value
 * @method string              getAdresse()                   Returns the current record's "adresse" value
 * @method string              getAdresse2()                  Returns the current record's "adresse2" value
 * @method string              getVille()                     Returns the current record's "ville" value
 * @method string              getCodePostal()                Returns the current record's "code_postal" value
 * @method string              getCodeInsee()                 Returns the current record's "code_insee" value
 * @method string              getTel()                       Returns the current record's "tel" value
 * @method string              getMail()                      Returns the current record's "mail" value
 * @method string              getPhoto()                     Returns the current record's "photo" value
 * @method string              getPhotoCrop()                 Returns the current record's "photo_crop" value
 * @method clob                getPresentation()              Returns the current record's "presentation" value
 * @method clob                getMissions()                  Returns the current record's "missions" value
 * @method clob                getBut()                       Returns the current record's "but" value
 * @method clob                getStrategie()                 Returns the current record's "strategie" value
 * @method string              getUrl()                       Returns the current record's "url" value
 * @method Profil              getProfil()                    Returns the current record's "Profil" value
 * @method Doctrine_Collection getMetier()                    Returns the current record's "Metier" collection
 * @method Doctrine_Collection getTheme()                     Returns the current record's "Theme" collection
 * @method Doctrine_Collection getCompetence()                Returns the current record's "Competence" collection
 * @method Doctrine_Collection getFiliere()                   Returns the current record's "Filiere" collection
 * @method Doctrine_Collection getProfilStructure()           Returns the current record's "ProfilStructure" collection
 * @method Doctrine_Collection getEvent()                     Returns the current record's "Event" collection
 * @method Doctrine_Collection getEventStructure()            Returns the current record's "EventStructure" collection
 * @method Doctrine_Collection getStructureTheme()            Returns the current record's "StructureTheme" collection
 * @method Doctrine_Collection getStructureFiliere()          Returns the current record's "StructureFiliere" collection
 * @method Doctrine_Collection getStructureCompetence()       Returns the current record's "StructureCompetence" collection
 * @method Doctrine_Collection getStructureMetier()           Returns the current record's "StructureMetier" collection
 * @method Doctrine_Collection getStructureContact()          Returns the current record's "StructureContact" collection
 * @method Doctrine_Collection getProjet()                    Returns the current record's "Projet" collection
 * @method Doctrine_Collection getProjetStructure()           Returns the current record's "ProjetStructure" collection
 * @method Doctrine_Collection getProjetStructurePartenaire() Returns the current record's "ProjetStructurePartenaire" collection
 * @method Structure           setCreateurId()                Sets the current record's "createur_id" value
 * @method Structure           setNom()                       Sets the current record's "nom" value
 * @method Structure           setAdresse()                   Sets the current record's "adresse" value
 * @method Structure           setAdresse2()                  Sets the current record's "adresse2" value
 * @method Structure           setVille()                     Sets the current record's "ville" value
 * @method Structure           setCodePostal()                Sets the current record's "code_postal" value
 * @method Structure           setCodeInsee()                 Sets the current record's "code_insee" value
 * @method Structure           setTel()                       Sets the current record's "tel" value
 * @method Structure           setMail()                      Sets the current record's "mail" value
 * @method Structure           setPhoto()                     Sets the current record's "photo" value
 * @method Structure           setPhotoCrop()                 Sets the current record's "photo_crop" value
 * @method Structure           setPresentation()              Sets the current record's "presentation" value
 * @method Structure           setMissions()                  Sets the current record's "missions" value
 * @method Structure           setBut()                       Sets the current record's "but" value
 * @method Structure           setStrategie()                 Sets the current record's "strategie" value
 * @method Structure           setUrl()                       Sets the current record's "url" value
 * @method Structure           setProfil()                    Sets the current record's "Profil" value
 * @method Structure           setMetier()                    Sets the current record's "Metier" collection
 * @method Structure           setTheme()                     Sets the current record's "Theme" collection
 * @method Structure           setCompetence()                Sets the current record's "Competence" collection
 * @method Structure           setFiliere()                   Sets the current record's "Filiere" collection
 * @method Structure           setProfilStructure()           Sets the current record's "ProfilStructure" collection
 * @method Structure           setEvent()                     Sets the current record's "Event" collection
 * @method Structure           setEventStructure()            Sets the current record's "EventStructure" collection
 * @method Structure           setStructureTheme()            Sets the current record's "StructureTheme" collection
 * @method Structure           setStructureFiliere()          Sets the current record's "StructureFiliere" collection
 * @method Structure           setStructureCompetence()       Sets the current record's "StructureCompetence" collection
 * @method Structure           setStructureMetier()           Sets the current record's "StructureMetier" collection
 * @method Structure           setStructureContact()          Sets the current record's "StructureContact" collection
 * @method Structure           setProjet()                    Sets the current record's "Projet" collection
 * @method Structure           setProjetStructure()           Sets the current record's "ProjetStructure" collection
 * @method Structure           setProjetStructurePartenaire() Sets the current record's "ProjetStructurePartenaire" collection
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStructure extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('structure');
        $this->hasColumn('createur_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('adresse', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('adresse2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ville', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('code_postal', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('code_insee', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('tel', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('mail', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('photo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('photo_crop', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('presentation', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('missions', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('but', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('strategie', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profil', array(
             'local' => 'createur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Metier', array(
             'refClass' => 'StructureMetier',
             'local' => 'structure_id',
             'foreign' => 'metier_id'));

        $this->hasMany('Theme', array(
             'refClass' => 'StructureTheme',
             'local' => 'structure_id',
             'foreign' => 'theme_id'));

        $this->hasMany('Competence', array(
             'refClass' => 'StructureCompetence',
             'local' => 'structure_id',
             'foreign' => 'competence_id'));

        $this->hasMany('Filiere', array(
             'refClass' => 'StructureFiliere',
             'local' => 'structure_id',
             'foreign' => 'filiere_id'));

        $this->hasMany('ProfilStructure', array(
             'local' => 'id',
             'foreign' => 'structure_id'));

        $this->hasMany('Event', array(
             'refClass' => 'EventStructure',
             'local' => 'structure_id',
             'foreign' => 'event_id'));

        $this->hasMany('EventStructure', array(
             'local' => 'id',
             'foreign' => 'structure_id'));

        $this->hasMany('StructureTheme', array(
             'local' => 'id',
             'foreign' => 'structure_id'));

        $this->hasMany('StructureFiliere', array(
             'local' => 'id',
             'foreign' => 'structure_id'));

        $this->hasMany('StructureCompetence', array(
             'local' => 'id',
             'foreign' => 'structure_id'));

        $this->hasMany('StructureMetier', array(
             'local' => 'id',
             'foreign' => 'structure_id'));

        $this->hasMany('StructureContact', array(
             'local' => 'id',
             'foreign' => 'structure_id'));

        $this->hasMany('Projet', array(
             'refClass' => 'ProjetStructure',
             'local' => 'structure_id',
             'foreign' => 'projet_id'));

        $this->hasMany('ProjetStructure', array(
             'local' => 'id',
             'foreign' => 'structure_id'));

        $this->hasMany('ProjetStructurePartenaire', array(
             'local' => 'id',
             'foreign' => 'structure_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nom',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $geolocatable0 = new Doctrine_Template_Geolocatable(array(
             'fields' => 
             array(
              0 => 'adresse',
              1 => 'ville',
              2 => 'code_postal',
             ),
             ));
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
        $this->actAs($geolocatable0);
    }
}