<?php

/**
 * BaseStats
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property integer $total
 * 
 * @method integer getId()    Returns the current record's "id" value
 * @method string  getType()  Returns the current record's "type" value
 * @method integer getTotal() Returns the current record's "total" value
 * @method Stats   setId()    Sets the current record's "id" value
 * @method Stats   setType()  Sets the current record's "type" value
 * @method Stats   setTotal() Sets the current record's "total" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStats extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stats');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('total', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('type', array(
             'fields' => 
             array(
              0 => 'type',
             ),
             ));
        $this->index('created_at', array(
             'fields' => 
             array(
              0 => 'created_at',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}