<?php

/**
 * BaseStructureFiliere
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $structure_id
 * @property integer $filiere_id
 * @property Structure $Structure
 * @property Filiere $Filiere
 * 
 * @method integer          getId()           Returns the current record's "id" value
 * @method integer          getStructureId()  Returns the current record's "structure_id" value
 * @method integer          getFiliereId()    Returns the current record's "filiere_id" value
 * @method Structure        getStructure()    Returns the current record's "Structure" value
 * @method Filiere          getFiliere()      Returns the current record's "Filiere" value
 * @method StructureFiliere setId()           Sets the current record's "id" value
 * @method StructureFiliere setStructureId()  Sets the current record's "structure_id" value
 * @method StructureFiliere setFiliereId()    Sets the current record's "filiere_id" value
 * @method StructureFiliere setStructure()    Sets the current record's "Structure" value
 * @method StructureFiliere setFiliere()      Sets the current record's "Filiere" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStructureFiliere extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('structure_filiere');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('structure_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('filiere_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Structure', array(
             'local' => 'structure_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Filiere', array(
             'local' => 'filiere_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}