<?php

/**
 * BaseProfilProjet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $profil_id
 * @property integer $projet_id
 * @property enum $role
 * @property timestamp $date
 * @property Profil $Profil
 * @property Projet $Projet
 * 
 * @method integer      getId()        Returns the current record's "id" value
 * @method integer      getProfilId()  Returns the current record's "profil_id" value
 * @method integer      getProjetId()  Returns the current record's "projet_id" value
 * @method enum         getRole()      Returns the current record's "role" value
 * @method timestamp    getDate()      Returns the current record's "date" value
 * @method Profil       getProfil()    Returns the current record's "Profil" value
 * @method Projet       getProjet()    Returns the current record's "Projet" value
 * @method ProfilProjet setId()        Sets the current record's "id" value
 * @method ProfilProjet setProfilId()  Sets the current record's "profil_id" value
 * @method ProfilProjet setProjetId()  Sets the current record's "projet_id" value
 * @method ProfilProjet setRole()      Sets the current record's "role" value
 * @method ProfilProjet setDate()      Sets the current record's "date" value
 * @method ProfilProjet setProfil()    Sets the current record's "Profil" value
 * @method ProfilProjet setProjet()    Sets the current record's "Projet" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfilProjet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profil_projet');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('profil_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('projet_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('role', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'referent',
              1 => 'contributeur',
              2 => 'observateur',
             ),
             'default' => 'observateur',
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('date', array(
             'fields' => 
             array(
              0 => 'date',
             ),
             ));
        $this->index('role', array(
             'fields' => 
             array(
              0 => 'role',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profil', array(
             'local' => 'profil_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Projet', array(
             'local' => 'projet_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}