<?php

/**
 * BaseAnnonceFiliere
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $annonce_id
 * @property integer $filiere_id
 * @property Annonce $Annonce
 * @property Filiere $Filiere
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method integer        getAnnonceId()  Returns the current record's "annonce_id" value
 * @method integer        getFiliereId()  Returns the current record's "filiere_id" value
 * @method Annonce        getAnnonce()    Returns the current record's "Annonce" value
 * @method Filiere        getFiliere()    Returns the current record's "Filiere" value
 * @method AnnonceFiliere setId()         Sets the current record's "id" value
 * @method AnnonceFiliere setAnnonceId()  Sets the current record's "annonce_id" value
 * @method AnnonceFiliere setFiliereId()  Sets the current record's "filiere_id" value
 * @method AnnonceFiliere setAnnonce()    Sets the current record's "Annonce" value
 * @method AnnonceFiliere setFiliere()    Sets the current record's "Filiere" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnnonceFiliere extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('annonce_filiere');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('annonce_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('filiere_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Annonce', array(
             'local' => 'annonce_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Filiere', array(
             'local' => 'filiere_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}