<?php

/**
 * BaseStory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $profil_id
 * @property integer $object_id
 * @property string $object_model
 * @property integer $relation_id
 * @property string $relation_model
 * @property string $story_i18n
 * @property string $type
 * @property string $url
 * @property clob $params
 * @property Profil $Profil
 * @property Doctrine_Collection $Buddies
 * @property Doctrine_Collection $Invitation
 * @property Doctrine_Collection $ProfilProfil
 * @property Doctrine_Collection $StoryBuddies
 * @property Doctrine_Collection $StoryPictures
 * @property Doctrine_Collection $Ressource
 * @property Doctrine_Collection $Event
 * @property Doctrine_Collection $Projet
 * 
 * @method integer             getProfilId()        Returns the current record's "profil_id" value
 * @method integer             getObjectId()        Returns the current record's "object_id" value
 * @method string              getObjectModel()     Returns the current record's "object_model" value
 * @method integer             getRelationId()      Returns the current record's "relation_id" value
 * @method string              getRelationModel()   Returns the current record's "relation_model" value
 * @method string              getStoryI18n()       Returns the current record's "story_i18n" value
 * @method string              getType()            Returns the current record's "type" value
 * @method string              getUrl()             Returns the current record's "url" value
 * @method clob                getParams()          Returns the current record's "params" value
 * @method Profil              getProfil()          Returns the current record's "Profil" value
 * @method Doctrine_Collection getBuddies()         Returns the current record's "Buddies" collection
 * @method Doctrine_Collection getInvitation()      Returns the current record's "Invitation" collection
 * @method Doctrine_Collection getProfilProfil()    Returns the current record's "ProfilProfil" collection
 * @method Doctrine_Collection getStoryBuddies()    Returns the current record's "StoryBuddies" collection
 * @method Doctrine_Collection getStoryPictures()   Returns the current record's "StoryPictures" collection
 * @method Doctrine_Collection getRessource()       Returns the current record's "Ressource" collection
 * @method Doctrine_Collection getEvent()           Returns the current record's "Event" collection
 * @method Doctrine_Collection getProjetIdee()      Returns the current record's "ProjetIdee" collection
 * @method Doctrine_Collection getCommentaire()     Returns the current record's "Commentaire" collection
 * @method Doctrine_Collection getCommentaireVote() Returns the current record's "CommentaireVote" collection
 * @method Doctrine_Collection getProjet()          Returns the current record's "Projet" collection
 * @method Story               setProfilId()        Sets the current record's "profil_id" value
 * @method Story               setObjectId()        Sets the current record's "object_id" value
 * @method Story               setObjectModel()     Sets the current record's "object_model" value
 * @method Story               setRelationId()      Sets the current record's "relation_id" value
 * @method Story               setRelationModel()   Sets the current record's "relation_model" value
 * @method Story               setStoryI18n()       Sets the current record's "story_i18n" value
 * @method Story               setType()            Sets the current record's "type" value
 * @method Story               setUrl()             Sets the current record's "url" value
 * @method Story               setParams()          Sets the current record's "params" value
 * @method Story               setProfil()          Sets the current record's "Profil" value
 * @method Story               setBuddies()         Sets the current record's "Buddies" collection
 * @method Story               setInvitation()      Sets the current record's "Invitation" collection
 * @method Story               setProfilProfil()    Sets the current record's "ProfilProfil" collection
 * @method Story               setStoryBuddies()    Sets the current record's "StoryBuddies" collection
 * @method Story               setStoryPictures()   Sets the current record's "StoryPictures" collection
 * @method Story               setRessource()       Sets the current record's "Ressource" collection
 * @method Story               setEvent()           Sets the current record's "Event" collection
 * @method Story               setProjetIdee()      Sets the current record's "ProjetIdee" collection
 * @method Story               setCommentaire()     Sets the current record's "Commentaire" collection
 * @method Story               setCommentaireVote() Sets the current record's "CommentaireVote" collection
 * @method Story               setProjet()          Sets the current record's "Projet" collectionIdee
 * @property Doctrine_Collection $Commentaire
 * @property Doctrine_Collection $CommentaireVote
 * @property Doctrine_Collection $Projet
 * 
 * @method integer             getProfilId()        Returns the current record's "profil_id" value
 * @method integer             getObjectId()        Returns the current record's "object_id" value
 * @method string              getObjectModel()     Returns the current record's "object_model" value
 * @method integer             getRelationId()      Returns the current record's "relation_id" value
 * @method string              getRelationModel()   Returns the current record's "relation_model" value
 * @method string              getStoryI18n()       Returns the current record's "story_i18n" value
 * @method string              getType()            Returns the current record's "type" value
 * @method string              getUrl()             Returns the current record's "url" value
 * @method clob                getParams()          Returns the current record's "params" value
 * @method Profil              getProfil()          Returns the current record's "Profil" value
 * @method Doctrine_Collection getBuddies()         Returns the current record's "Buddies" collection
 * @method Doctrine_Collection getInvitation()      Returns the current record's "Invitation" collection
 * @method Doctrine_Collection getProfilProfil()    Returns the current record's "ProfilProfil" collection
 * @method Doctrine_Collection getStoryBuddies()    Returns the current record's "StoryBuddies" collection
 * @method Doctrine_Collection getStoryPictures()   Returns the current record's "StoryPictures" collection
 * @method Doctrine_Collection getRessource()       Returns the current record's "Ressource" collection
 * @method Doctrine_Collection getEvent()           Returns the current record's "Event" collection
 * @method Doctrine_Collection getProjetIdee()      Returns the current record's "ProjetIdee" collection
 * @method Doctrine_Collection getCommentaire()     Returns the current record's "Commentaire" collection
 * @method Doctrine_Collection getCommentaireVote() Returns the current record's "CommentaireVote" collection
 * @method Doctrine_Collection getProjet()          Returns the current record's "Projet" collection
 * @method Story               setProfilId()        Sets the current record's "profil_id" value
 * @method Story               setObjectId()        Sets the current record's "object_id" value
 * @method Story               setObjectModel()     Sets the current record's "object_model" value
 * @method Story               setRelationId()      Sets the current record's "relation_id" value
 * @method Story               setRelationModel()   Sets the current record's "relation_model" value
 * @method Story               setStoryI18n()       Sets the current record's "story_i18n" value
 * @method Story               setType()            Sets the current record's "type" value
 * @method Story               setUrl()             Sets the current record's "url" value
 * @method Story               setParams()          Sets the current record's "params" value
 * @method Story               setProfil()          Sets the current record's "Profil" value
 * @method Story               setBuddies()         Sets the current record's "Buddies" collection
 * @method Story               setInvitation()      Sets the current record's "Invitation" collection
 * @method Story               setProfilProfil()    Sets the current record's "ProfilProfil" collection
 * @method Story               setStoryBuddies()    Sets the current record's "StoryBuddies" collection
 * @method Story               setStoryPictures()   Sets the current record's "StoryPictures" collection
 * @method Story               setRessource()       Sets the current record's "Ressource" collection
 * @method Story               setEvent()           Sets the current record's "Event" collection
 * @method Story               setProjetIdee()      Sets the current record's "ProjetIdee" collection
 * @method Story               setCommentaire()     Sets the current record's "Commentaire" collection
 * @method Story               setCommentaireVote() Sets the current record's "CommentaireVote" collection
 * @method Story               setProjet()          Sets the current record's "Projet" collection
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('story');
        $this->hasColumn('profil_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('object_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('object_model', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('relation_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('relation_model', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('story_i18n', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('type', 'string', 25, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('params', 'clob', null, array(
             'type' => 'clob',
             ));


        $this->index('object_id', array(
             'fields' => 
             array(
              0 => 'object_id',
             ),
             ));
        $this->index('object_model', array(
             'fields' => 
             array(
              0 => 'object_model',
             ),
             ));
        $this->index('relation_id', array(
             'fields' => 
             array(
              0 => 'relation_id',
             ),
             ));
        $this->index('relation_model', array(
             'fields' => 
             array(
              0 => 'relation_model',
             ),
             ));
        $this->index('type', array(
             'fields' => 
             array(
              0 => 'type',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profil', array(
             'local' => 'profil_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Profil as Buddies', array(
             'refClass' => 'StoryBuddies',
             'local' => 'story_id',
             'foreign' => 'profil_id'));

        $this->hasMany('Invitation', array(
             'local' => 'id',
             'foreign' => 'story_id'));

        $this->hasMany('ProfilProfil', array(
             'local' => 'id',
             'foreign' => 'story_id'));

        $this->hasMany('StoryBuddies', array(
             'local' => 'id',
             'foreign' => 'story_id'));

        $this->hasMany('StoryPictures', array(
             'local' => 'id',
             'foreign' => 'story_id'));

        $this->hasMany('Ressource', array(
             'local' => 'id',
             'foreign' => 'story_id'));

        $this->hasMany('Event', array(
             'local' => 'id',
             'foreign' => 'story_id'));

        $this->hasMany('ProjetIdee', array(
             'local' => 'id',
             'foreign' => 'story_id'));

        $this->hasMany('Commentaire', array(
             'local' => 'id',
             'foreign' => 'story_id'));

        $this->hasMany('CommentaireVote', array(
             'local' => 'id',
             'foreign' => 'story_id'));

        $this->hasMany('Projet', array(
             'local' => 'id',
             'foreign' => 'story_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}