<?php

/**
 * BaseRessourceTheme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $ressource_id
 * @property integer $theme_id
 * @property Ressource $Ressource
 * @property Theme $Theme
 * 
 * @method integer        getId()           Returns the current record's "id" value
 * @method integer        getRessourceId()  Returns the current record's "ressource_id" value
 * @method integer        getThemeId()      Returns the current record's "theme_id" value
 * @method Ressource      getRessource()    Returns the current record's "Ressource" value
 * @method Theme          getTheme()        Returns the current record's "Theme" value
 * @method RessourceTheme setId()           Sets the current record's "id" value
 * @method RessourceTheme setRessourceId()  Sets the current record's "ressource_id" value
 * @method RessourceTheme setThemeId()      Sets the current record's "theme_id" value
 * @method RessourceTheme setRessource()    Sets the current record's "Ressource" value
 * @method RessourceTheme setTheme()        Sets the current record's "Theme" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRessourceTheme extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ressource_theme');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ressource_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('theme_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ressource', array(
             'local' => 'ressource_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Theme', array(
             'local' => 'theme_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}