<?php

/**
 * BaseRessource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $createur_id
 * @property integer $story_id
 * @property integer $projet_id
 * @property integer $event_id
 * @property string $nom
 * @property clob $resume
 * @property string $fichier
 * @property string $video
 * @property string $source
 * @property timestamp $date
 * @property Profil $Profil
 * @property Projet $Projet
 * @property Event $Event
 * @property Story $Story
 * @property Doctrine_Collection $Filiere
 * @property Doctrine_Collection $Theme
 * @property Doctrine_Collection $RessourceFiliere
 * @property Doctrine_Collection $RessourceTheme
 * 
 * @method integer             getCreateurId()       Returns the current record's "createur_id" value
 * @method integer             getStoryId()          Returns the current record's "story_id" value
 * @method integer             getProjetId()         Returns the current record's "projet_id" value
 * @method integer             getEventId()          Returns the current record's "event_id" value
 * @method string              getNom()              Returns the current record's "nom" value
 * @method clob                getResume()           Returns the current record's "resume" value
 * @method string              getFichier()          Returns the current record's "fichier" value
 * @method string              getVideo()            Returns the current record's "video" value
 * @method string              getSource()           Returns the current record's "source" value
 * @method timestamp           getDate()             Returns the current record's "date" value
 * @method Profil              getProfil()           Returns the current record's "Profil" value
 * @method Projet              getProjet()           Returns the current record's "Projet" value
 * @method Event               getEvent()            Returns the current record's "Event" value
 * @method Story               getStory()            Returns the current record's "Story" value
 * @method Doctrine_Collection getFiliere()          Returns the current record's "Filiere" collection
 * @method Doctrine_Collection getTheme()            Returns the current record's "Theme" collection
 * @method Doctrine_Collection getRessourceFiliere() Returns the current record's "RessourceFiliere" collection
 * @method Doctrine_Collection getRessourceTheme()   Returns the current record's "RessourceTheme" collection
 * @method Ressource           setCreateurId()       Sets the current record's "createur_id" value
 * @method Ressource           setStoryId()          Sets the current record's "story_id" value
 * @method Ressource           setProjetId()         Sets the current record's "projet_id" value
 * @method Ressource           setEventId()          Sets the current record's "event_id" value
 * @method Ressource           setNom()              Sets the current record's "nom" value
 * @method Ressource           setResume()           Sets the current record's "resume" value
 * @method Ressource           setFichier()          Sets the current record's "fichier" value
 * @method Ressource           setVideo()            Sets the current record's "video" value
 * @method Ressource           setSource()           Sets the current record's "source" value
 * @method Ressource           setDate()             Sets the current record's "date" value
 * @method Ressource           setProfil()           Sets the current record's "Profil" value
 * @method Ressource           setProjet()           Sets the current record's "Projet" value
 * @method Ressource           setEvent()            Sets the current record's "Event" value
 * @method Ressource           setStory()            Sets the current record's "Story" value
 * @method Ressource           setFiliere()          Sets the current record's "Filiere" collection
 * @method Ressource           setTheme()            Sets the current record's "Theme" collection
 * @method Ressource           setRessourceFiliere() Sets the current record's "RessourceFiliere" collection
 * @method Ressource           setRessourceTheme()   Sets the current record's "RessourceTheme" collection
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRessource extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ressource');
        $this->hasColumn('createur_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('story_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('projet_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('resume', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('fichier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('video', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('source', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('date', array(
             'fields' => 
             array(
              0 => 'date',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profil', array(
             'local' => 'createur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Projet', array(
             'local' => 'projet_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Story', array(
             'local' => 'story_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('Filiere', array(
             'refClass' => 'RessourceFiliere',
             'local' => 'ressource_id',
             'foreign' => 'filiere_id'));

        $this->hasMany('Theme', array(
             'refClass' => 'RessourceTheme',
             'local' => 'ressource_id',
             'foreign' => 'theme_id'));

        $this->hasMany('RessourceFiliere', array(
             'local' => 'id',
             'foreign' => 'ressource_id'));

        $this->hasMany('RessourceTheme', array(
             'local' => 'id',
             'foreign' => 'ressource_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nom',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}