<?php

/**
 * BaseEventTheme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $event_id
 * @property integer $theme_id
 * @property Event $Event
 * @property Theme $Theme
 * 
 * @method integer    getId()       Returns the current record's "id" value
 * @method integer    getEventId()  Returns the current record's "event_id" value
 * @method integer    getThemeId()  Returns the current record's "theme_id" value
 * @method Event      getEvent()    Returns the current record's "Event" value
 * @method Theme      getTheme()    Returns the current record's "Theme" value
 * @method EventTheme setId()       Sets the current record's "id" value
 * @method EventTheme setEventId()  Sets the current record's "event_id" value
 * @method EventTheme setThemeId()  Sets the current record's "theme_id" value
 * @method EventTheme setEvent()    Sets the current record's "Event" value
 * @method EventTheme setTheme()    Sets the current record's "Theme" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventTheme extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_theme');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('theme_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Theme', array(
             'local' => 'theme_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}