<?php

/**
 * BaseEventCompetence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $event_id
 * @property integer $competence_id
 * @property Event $Event
 * @property Competence $Competence
 * 
 * @method integer         getId()            Returns the current record's "id" value
 * @method integer         getEventId()       Returns the current record's "event_id" value
 * @method integer         getCompetenceId()  Returns the current record's "competence_id" value
 * @method Event           getEvent()         Returns the current record's "Event" value
 * @method Competence      getCompetence()    Returns the current record's "Competence" value
 * @method EventCompetence setId()            Sets the current record's "id" value
 * @method EventCompetence setEventId()       Sets the current record's "event_id" value
 * @method EventCompetence setCompetenceId()  Sets the current record's "competence_id" value
 * @method EventCompetence setEvent()         Sets the current record's "Event" value
 * @method EventCompetence setCompetence()    Sets the current record's "Competence" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventCompetence extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_competence');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('competence_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Competence', array(
             'local' => 'competence_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}