<?php

/**
 * BaseRessourceFiliere
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $ressource_id
 * @property integer $filiere_id
 * @property Ressource $Ressource
 * @property Filiere $Filiere
 * 
 * @method integer          getId()           Returns the current record's "id" value
 * @method integer          getRessourceId()  Returns the current record's "ressource_id" value
 * @method integer          getFiliereId()    Returns the current record's "filiere_id" value
 * @method Ressource        getRessource()    Returns the current record's "Ressource" value
 * @method Filiere          getFiliere()      Returns the current record's "Filiere" value
 * @method RessourceFiliere setId()           Sets the current record's "id" value
 * @method RessourceFiliere setRessourceId()  Sets the current record's "ressource_id" value
 * @method RessourceFiliere setFiliereId()    Sets the current record's "filiere_id" value
 * @method RessourceFiliere setRessource()    Sets the current record's "Ressource" value
 * @method RessourceFiliere setFiliere()      Sets the current record's "Filiere" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRessourceFiliere extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ressource_filiere');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ressource_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('filiere_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ressource', array(
             'local' => 'ressource_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Filiere', array(
             'local' => 'filiere_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}