<?php

/**
 * BaseProjetCompetence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $projet_id
 * @property integer $competence_id
 * @property Projet $Projet
 * @property Competence $Competence
 * 
 * @method integer          getId()            Returns the current record's "id" value
 * @method integer          getProjetId()      Returns the current record's "projet_id" value
 * @method integer          getCompetenceId()  Returns the current record's "competence_id" value
 * @method Projet           getProjet()        Returns the current record's "Projet" value
 * @method Competence       getCompetence()    Returns the current record's "Competence" value
 * @method ProjetCompetence setId()            Sets the current record's "id" value
 * @method ProjetCompetence setProjetId()      Sets the current record's "projet_id" value
 * @method ProjetCompetence setCompetenceId()  Sets the current record's "competence_id" value
 * @method ProjetCompetence setProjet()        Sets the current record's "Projet" value
 * @method ProjetCompetence setCompetence()    Sets the current record's "Competence" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjetCompetence extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('projet_competence');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('projet_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('competence_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Projet', array(
             'local' => 'projet_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Competence', array(
             'local' => 'competence_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}