<?php

/**
 * BaseCommentaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $profil_id
 * @property integer $story_id
 * @property integer $content_id
 * @property string $content_type
 * @property clob $message
 * @property Profil $Profil
 * @property Story $Story
 * 
 * @method integer     getProfilId()     Returns the current record's "profil_id" value
 * @method integer     getStoryId()      Returns the current record's "story_id" value
 * @method integer     getContentId()    Returns the current record's "content_id" value
 * @method string      getContentType()  Returns the current record's "content_type" value
 * @method clob        getMessage()      Returns the current record's "message" value
 * @method Profil      getProfil()       Returns the current record's "Profil" value
 * @method Story       getStory()        Returns the current record's "Story" value
 * @method Commentaire setProfilId()     Sets the current record's "profil_id" value
 * @method Commentaire setStoryId()      Sets the current record's "story_id" value
 * @method Commentaire setContentId()    Sets the current record's "content_id" value
 * @method Commentaire setContentType()  Sets the current record's "content_type" value
 * @method Commentaire setMessage()      Sets the current record's "message" value
 * @method Commentaire setProfil()       Sets the current record's "Profil" value
 * @method Commentaire setStory()        Sets the current record's "Story" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommentaire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('commentaire');
        $this->hasColumn('profil_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('story_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('content_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('content_type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('message', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profil', array(
             'local' => 'profil_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Story', array(
             'local' => 'story_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}