<?php

/**
 * BaseStructureContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $structure_id
 * @property integer $profil_id
 * @property enum $civilite
 * @property string $nom
 * @property string $prenom
 * @property string $fonction
 * @property string $mail
 * @property string $phone
 * @property boolean $requalif
 * @property Structure $Structure
 * @property Profil $Profil
 * 
 * @method integer          getStructureId()  Returns the current record's "structure_id" value
 * @method integer          getProfilId()     Returns the current record's "profil_id" value
 * @method enum             getCivilite()     Returns the current record's "civilite" value
 * @method string           getNom()          Returns the current record's "nom" value
 * @method string           getPrenom()       Returns the current record's "prenom" value
 * @method string           getFonction()     Returns the current record's "fonction" value
 * @method string           getMail()         Returns the current record's "mail" value
 * @method string           getPhone()        Returns the current record's "phone" value
 * @method boolean          getRequalif()     Returns the current record's "requalif" value
 * @method Structure        getStructure()    Returns the current record's "Structure" value
 * @method Profil           getProfil()       Returns the current record's "Profil" value
 * @method StructureContact setStructureId()  Sets the current record's "structure_id" value
 * @method StructureContact setProfilId()     Sets the current record's "profil_id" value
 * @method StructureContact setCivilite()     Sets the current record's "civilite" value
 * @method StructureContact setNom()          Sets the current record's "nom" value
 * @method StructureContact setPrenom()       Sets the current record's "prenom" value
 * @method StructureContact setFonction()     Sets the current record's "fonction" value
 * @method StructureContact setMail()         Sets the current record's "mail" value
 * @method StructureContact setPhone()        Sets the current record's "phone" value
 * @method StructureContact setRequalif()     Sets the current record's "requalif" value
 * @method StructureContact setStructure()    Sets the current record's "Structure" value
 * @method StructureContact setProfil()       Sets the current record's "Profil" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStructureContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('structure_contact');
        $this->hasColumn('structure_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('profil_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('civilite', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'm',
              1 => 'melle',
              2 => 'mme',
             ),
             'default' => 'm',
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('prenom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('fonction', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mail', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('phone', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('requalif', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Structure', array(
             'local' => 'structure_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Profil', array(
             'local' => 'profil_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}