<?php

/**
 * BaseProjetStructurePartenaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $projet_id
 * @property integer $structure_id
 * @property Projet $Projet
 * @property Structure $Structure
 * 
 * @method integer                   getId()           Returns the current record's "id" value
 * @method integer                   getProjetId()     Returns the current record's "projet_id" value
 * @method integer                   getStructureId()  Returns the current record's "structure_id" value
 * @method Projet                    getProjet()       Returns the current record's "Projet" value
 * @method Structure                 getStructure()    Returns the current record's "Structure" value
 * @method ProjetStructurePartenaire setId()           Sets the current record's "id" value
 * @method ProjetStructurePartenaire setProjetId()     Sets the current record's "projet_id" value
 * @method ProjetStructurePartenaire setStructureId()  Sets the current record's "structure_id" value
 * @method ProjetStructurePartenaire setProjet()       Sets the current record's "Projet" value
 * @method ProjetStructurePartenaire setStructure()    Sets the current record's "Structure" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjetStructurePartenaire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('projet_structure_partenaire');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('projet_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('structure_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Projet', array(
             'local' => 'projet_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Structure', array(
             'local' => 'structure_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}