<?php

/**
 * BaseWishInvitation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $profil_id
 * @property integer $projet_id
 * @property boolean $hidden
 * @property Profil $Profil
 * @property Projet $Projet
 * 
 * @method integer        getId()        Returns the current record's "id" value
 * @method integer        getProfilId()  Returns the current record's "profil_id" value
 * @method integer        getProjetId()  Returns the current record's "projet_id" value
 * @method boolean        getHidden()    Returns the current record's "hidden" value
 * @method Profil         getProfil()    Returns the current record's "Profil" value
 * @method Projet         getProjet()    Returns the current record's "Projet" value
 * @method WishInvitation setId()        Sets the current record's "id" value
 * @method WishInvitation setProfilId()  Sets the current record's "profil_id" value
 * @method WishInvitation setProjetId()  Sets the current record's "projet_id" value
 * @method WishInvitation setHidden()    Sets the current record's "hidden" value
 * @method WishInvitation setProfil()    Sets the current record's "Profil" value
 * @method WishInvitation setProjet()    Sets the current record's "Projet" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWishInvitation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wish_invitation');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('profil_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('projet_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('hidden', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             'notnull' => true,
             ));


        $this->index('hidden', array(
             'fields' => 
             array(
              0 => 'hidden',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profil', array(
             'local' => 'profil_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Projet', array(
             'local' => 'projet_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}