<?php

/**
 * BaseSegmentCompetence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $segment_id
 * @property integer $competence_id
 * @property Segment $Segment
 * @property Competence $Competence
 * 
 * @method integer           getId()            Returns the current record's "id" value
 * @method integer           getSegmentId()     Returns the current record's "segment_id" value
 * @method integer           getCompetenceId()  Returns the current record's "competence_id" value
 * @method Segment           getSegment()       Returns the current record's "Segment" value
 * @method Competence        getCompetence()    Returns the current record's "Competence" value
 * @method SegmentCompetence setId()            Sets the current record's "id" value
 * @method SegmentCompetence setSegmentId()     Sets the current record's "segment_id" value
 * @method SegmentCompetence setCompetenceId()  Sets the current record's "competence_id" value
 * @method SegmentCompetence setSegment()       Sets the current record's "Segment" value
 * @method SegmentCompetence setCompetence()    Sets the current record's "Competence" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSegmentCompetence extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('segment_competence');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('segment_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('competence_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Segment', array(
             'local' => 'segment_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Competence', array(
             'local' => 'competence_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}