<?php

/**
 * BaseSegmentTheme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $segment_id
 * @property integer $theme_id
 * @property Segment $Segment
 * @property Theme $Theme
 * 
 * @method integer      getId()         Returns the current record's "id" value
 * @method integer      getSegmentId()  Returns the current record's "segment_id" value
 * @method integer      getThemeId()    Returns the current record's "theme_id" value
 * @method Segment      getSegment()    Returns the current record's "Segment" value
 * @method Theme        getTheme()      Returns the current record's "Theme" value
 * @method SegmentTheme setId()         Sets the current record's "id" value
 * @method SegmentTheme setSegmentId()  Sets the current record's "segment_id" value
 * @method SegmentTheme setThemeId()    Sets the current record's "theme_id" value
 * @method SegmentTheme setSegment()    Sets the current record's "Segment" value
 * @method SegmentTheme setTheme()      Sets the current record's "Theme" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSegmentTheme extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('segment_theme');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('segment_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('theme_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Segment', array(
             'local' => 'segment_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Theme', array(
             'local' => 'theme_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}