<?php

/**
 * BasePays
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property clob $description
 * @property string $photo
 * @property Doctrine_Collection $Commune
 * 
 * @method string              getNom()         Returns the current record's "nom" value
 * @method clob                getDescription() Returns the current record's "description" value
 * @method string              getPhoto()       Returns the current record's "photo" value
 * @method Doctrine_Collection getCommune()     Returns the current record's "Commune" collection
 * @method Pays                setNom()         Sets the current record's "nom" value
 * @method Pays                setDescription() Sets the current record's "description" value
 * @method Pays                setPhoto()       Sets the current record's "photo" value
 * @method Pays                setCommune()     Sets the current record's "Commune" collection
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePays extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pays');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('photo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Commune', array(
             'local' => 'id',
             'foreign' => 'pays_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nom',
             ),
             ));
        $this->actAs($sluggable0);
    }
}