<?php

/**
 * BaseHistorique
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $profil_id
 * @property enum $type
 * @property string $query
 * @property timestamp $date
 * @property Profil $Profil
 * 
 * @method integer    getId()        Returns the current record's "id" value
 * @method integer    getProfilId()  Returns the current record's "profil_id" value
 * @method enum       getType()      Returns the current record's "type" value
 * @method string     getQuery()     Returns the current record's "query" value
 * @method timestamp  getDate()      Returns the current record's "date" value
 * @method Profil     getProfil()    Returns the current record's "Profil" value
 * @method Historique setId()        Sets the current record's "id" value
 * @method Historique setProfilId()  Sets the current record's "profil_id" value
 * @method Historique setType()      Sets the current record's "type" value
 * @method Historique setQuery()     Sets the current record's "query" value
 * @method Historique setDate()      Sets the current record's "date" value
 * @method Historique setProfil()    Sets the current record's "Profil" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHistorique extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('historique');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('profil_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'profil',
              1 => 'projet',
              2 => 'structure',
              3 => 'document',
             ),
             ));
        $this->hasColumn('query', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('type', array(
             'fields' => 
             array(
              0 => 'type',
             ),
             ));
        $this->index('date', array(
             'fields' => 
             array(
              0 => 'date',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profil', array(
             'local' => 'profil_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}