<?php

/**
 * BaseAnnonceCategorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property Doctrine_Collection $Annonce
 * 
 * @method string              getNom()     Returns the current record's "nom" value
 * @method Doctrine_Collection getAnnonce() Returns the current record's "Annonce" collection
 * @method AnnonceCategorie    setNom()     Sets the current record's "nom" value
 * @method AnnonceCategorie    setAnnonce() Sets the current record's "Annonce" collection
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnnonceCategorie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('annonce_categorie');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Annonce', array(
             'local' => 'id',
             'foreign' => 'categorie_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nom',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}