<?php

/**
 * BaseEventFiliere
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $event_id
 * @property integer $filiere_id
 * @property Event $Event
 * @property Filiere $Filiere
 * 
 * @method integer      getId()         Returns the current record's "id" value
 * @method integer      getEventId()    Returns the current record's "event_id" value
 * @method integer      getFiliereId()  Returns the current record's "filiere_id" value
 * @method Event        getEvent()      Returns the current record's "Event" value
 * @method Filiere      getFiliere()    Returns the current record's "Filiere" value
 * @method EventFiliere setId()         Sets the current record's "id" value
 * @method EventFiliere setEventId()    Sets the current record's "event_id" value
 * @method EventFiliere setFiliereId()  Sets the current record's "filiere_id" value
 * @method EventFiliere setEvent()      Sets the current record's "Event" value
 * @method EventFiliere setFiliere()    Sets the current record's "Filiere" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventFiliere extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_filiere');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('filiere_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Filiere', array(
             'local' => 'filiere_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}