<?php

/**
 * BaseStructureMetier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $structure_id
 * @property integer $metier_id
 * @property Structure $Structure
 * @property Metier $Metier
 * 
 * @method integer         getId()           Returns the current record's "id" value
 * @method integer         getStructureId()  Returns the current record's "structure_id" value
 * @method integer         getMetierId()     Returns the current record's "metier_id" value
 * @method Structure       getStructure()    Returns the current record's "Structure" value
 * @method Metier          getMetier()       Returns the current record's "Metier" value
 * @method StructureMetier setId()           Sets the current record's "id" value
 * @method StructureMetier setStructureId()  Sets the current record's "structure_id" value
 * @method StructureMetier setMetierId()     Sets the current record's "metier_id" value
 * @method StructureMetier setStructure()    Sets the current record's "Structure" value
 * @method StructureMetier setMetier()       Sets the current record's "Metier" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStructureMetier extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('structure_metier');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('structure_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('metier_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Structure', array(
             'local' => 'structure_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Metier', array(
             'local' => 'metier_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}