<?php

/**
 * BaseInvitationEmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $email
 * @property integer $projet_id
 * @property integer $event_id
 * @property integer $inviteur_id
 * @property timestamp $date
 * @property Projet $Projet
 * @property Profil $Inviteur
 * @property Event $Event
 * 
 * @method integer         getId()          Returns the current record's "id" value
 * @method string          getEmail()       Returns the current record's "email" value
 * @method integer         getProjetId()    Returns the current record's "projet_id" value
 * @method integer         getEventId()     Returns the current record's "event_id" value
 * @method integer         getInviteurId()  Returns the current record's "inviteur_id" value
 * @method timestamp       getDate()        Returns the current record's "date" value
 * @method Projet          getProjet()      Returns the current record's "Projet" value
 * @method Profil          getInviteur()    Returns the current record's "Inviteur" value
 * @method Event           getEvent()       Returns the current record's "Event" value
 * @method InvitationEmail setId()          Sets the current record's "id" value
 * @method InvitationEmail setEmail()       Sets the current record's "email" value
 * @method InvitationEmail setProjetId()    Sets the current record's "projet_id" value
 * @method InvitationEmail setEventId()     Sets the current record's "event_id" value
 * @method InvitationEmail setInviteurId()  Sets the current record's "inviteur_id" value
 * @method InvitationEmail setDate()        Sets the current record's "date" value
 * @method InvitationEmail setProjet()      Sets the current record's "Projet" value
 * @method InvitationEmail setInviteur()    Sets the current record's "Inviteur" value
 * @method InvitationEmail setEvent()       Sets the current record's "Event" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInvitationEmail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('invitation_email');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('projet_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('inviteur_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('email', array(
             'fields' => 
             array(
              0 => 'email',
             ),
             ));
        $this->index('date', array(
             'fields' => 
             array(
              0 => 'date',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Projet', array(
             'local' => 'projet_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Profil as Inviteur', array(
             'local' => 'inviteur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}