<?php

/**
 * BaseConsultation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $doc_id
 * @property enum $type_id
 * @property string $ip_source
 * @property integer $visiteur_id
 * @property timestamp $date
 * @property Profil $Profil
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getDocId()       Returns the current record's "doc_id" value
 * @method enum         getTypeId()      Returns the current record's "type_id" value
 * @method string       getIpSource()    Returns the current record's "ip_source" value
 * @method integer      getVisiteurId()  Returns the current record's "visiteur_id" value
 * @method timestamp    getDate()        Returns the current record's "date" value
 * @method Profil       getProfil()      Returns the current record's "Profil" value
 * @method Consultation setId()          Sets the current record's "id" value
 * @method Consultation setDocId()       Sets the current record's "doc_id" value
 * @method Consultation setTypeId()      Sets the current record's "type_id" value
 * @method Consultation setIpSource()    Sets the current record's "ip_source" value
 * @method Consultation setVisiteurId()  Sets the current record's "visiteur_id" value
 * @method Consultation setDate()        Sets the current record's "date" value
 * @method Consultation setProfil()      Sets the current record's "Profil" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConsultation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('consultation');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('doc_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type_id', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'profil',
              1 => 'projet',
             ),
             ));
        $this->hasColumn('ip_source', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('visiteur_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('type_id', array(
             'fields' => 
             array(
              0 => 'type_id',
             ),
             ));
        $this->index('date', array(
             'fields' => 
             array(
              0 => 'date',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profil', array(
             'local' => 'visiteur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}