<?php

/**
 * BaseMailingFiliere
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $filiere_id
 * @property integer $mailing_id
 * @property Filiere $Filiere
 * @property Mailing $Mailing
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method integer        getFiliereId()  Returns the current record's "filiere_id" value
 * @method integer        getMailingId()  Returns the current record's "mailing_id" value
 * @method Filiere        getFiliere()    Returns the current record's "Filiere" value
 * @method Mailing        getMailing()    Returns the current record's "Mailing" value
 * @method MailingFiliere setId()         Sets the current record's "id" value
 * @method MailingFiliere setFiliereId()  Sets the current record's "filiere_id" value
 * @method MailingFiliere setMailingId()  Sets the current record's "mailing_id" value
 * @method MailingFiliere setFiliere()    Sets the current record's "Filiere" value
 * @method MailingFiliere setMailing()    Sets the current record's "Mailing" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMailingFiliere extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mailing_filiere');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('filiere_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mailing_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Filiere', array(
             'local' => 'filiere_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Mailing', array(
             'local' => 'mailing_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}