<?php

/**
 * BaseProfilMetier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $profil_id
 * @property integer $metier_id
 * @property Profil $Profil
 * @property Metier $Metier
 * 
 * @method integer      getId()        Returns the current record's "id" value
 * @method integer      getProfilId()  Returns the current record's "profil_id" value
 * @method integer      getMetierId()  Returns the current record's "metier_id" value
 * @method Profil       getProfil()    Returns the current record's "Profil" value
 * @method Metier       getMetier()    Returns the current record's "Metier" value
 * @method ProfilMetier setId()        Sets the current record's "id" value
 * @method ProfilMetier setProfilId()  Sets the current record's "profil_id" value
 * @method ProfilMetier setMetierId()  Sets the current record's "metier_id" value
 * @method ProfilMetier setProfil()    Sets the current record's "Profil" value
 * @method ProfilMetier setMetier()    Sets the current record's "Metier" value
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfilMetier extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profil_metier');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('profil_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('metier_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profil', array(
             'local' => 'profil_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Metier', array(
             'local' => 'metier_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}