<?php

/**
 * AnnonceCategorieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnnonceCategorieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnnonceCategorieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnnonceCategorie');
    }
}