<?php

/**
 * AnnonceFiliereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnnonceFiliereTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnnonceFiliereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnnonceFiliere');
    }
}