<?php

/**
 * EventThemeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventThemeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventThemeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventTheme');
    }
}