<?php

/**
 * EventAdminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventAdminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventAdminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventAdmin');
    }
}