<?php

/**
 * EventMetierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventMetierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventMetierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventMetier');
    }
}