<?php

/**
 * EventInvite
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EventInvite extends BaseEventInvite
{
	public function postSave($values)
	{
		// Create Story
		if($this->get("etat") !== "pending")
		{
			Story::publish(
				"default",
				"Event",
				$this->get("event_id"),
				$this->get("profil_id"),
				"joinpart",
				"",
				array("etat" => $this->get("etat")),
				array(),
				true
			);
		}
	}
}
