<?php

/**
 * EventFiliereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventFiliereTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventFiliereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventFiliere');
    }
}