<?php

/**
 * EventInviteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventInviteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventInviteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventInvite');
    }
}