<?php

/**
 * Feedback
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Feedback extends BaseFeedback
{
	public function __getStatus()
	{
		switch($this->getStatus())
		{
			case "new";
				return "Nouveau";
			break;
			case "acknowledged";
				return "Pris en considération par l'équipe";
			break;
			case "prod";
				return "Mis en place";
			break;
		}
	}
	
	public function flushComments()
	{
		return Doctrine_Query::create()->delete('Commentaire c')->where("c.content_type = 'feedback'")->andWhere("c.content_id = ?", $this->getId())->execute();
	}
	
	public function getCountVote()
	{
		return Doctrine_Query::create()->from('CommentaireVote v')->where("v.content_type = 'feedback'")->andWhere("v.content_id = ?", $this->getId())->count();
	}
	
	public function getCountComment()
	{
		return Doctrine_Query::create()->from('Commentaire c')->where("c.content_type = 'feedback'")->andWhere("c.content_id = ?", $this->getId())->count();
	}
}
