<?php

/**
 * HomeNewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HomeNewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HomeNewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HomeNews');
    }
}