<?php

/**
 * MailingSegmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailingSegmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailingSegmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MailingSegment');
    }
}