<?php

/**
 * MailingFiliereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailingFiliereTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailingFiliereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MailingFiliere');
    }
}