<?php

/**
 * MailingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mailing');
    }
}