<?php

/**
 * ProjetCompetence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProjetCompetence extends BaseProjetCompetence
{
	public function getMatchingSkills($profil_id)
	{
		$Query = Doctrine_Query::create()
								->from('ProjetCompetence p')
								->innerJoin("p.ProfilCompetence g")
								->where('g.profil_id = ?', $profil_id)
								->andWhere('p.projet_id = ?', $this->getProjetId())
								->orderBy("RANDOM()")
								->execute();

		$return = array();
		
		foreach($Query as $mm)
		{
			$return[] = $mm->getCompetence();	
		}
		
		return $return;
	}
}
