<?php

/**
 * ProjetIdee
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProjetIdee extends BaseProjetIdee
{
	public function postInsert($values)
	{
		// Create Story
		if($this->get("projet_id"))
			Story::set_relation("Projet", $this->get("projet_id"));
		elseif($this->get("event_id"))
			Story::set_relation("Event", $this->get("event_id"));

		Story::publish(
						"default",
						"ProjetIdee",
						$this->get("id"),
						sfContext::getInstance()->getUser()->getId(),
						"idea"
		);
	}

	public function __getStatus()
	{
		switch($this->getStatus())
		{
			case "new";
				return "Nouveau";
			break;
			case "acknowledged";
				return "Pris en considération par l'équipe";
			break;
			case "prod";
				return "Mis en place";
			break;
		}
	}

	public function flushComments()
	{
		return Doctrine_Query::create()->delete('Commentaire c')->where("c.content_type = 'idea'")->andWhere("c.content_id = ?", $this->getId())->execute();
	}

	public function getCountVote()
	{
		return Doctrine_Query::create()->from('CommentaireVote v')->where("v.content_type = 'idea'")->andWhere("v.content_id = ?", $this->getId())->count();
	}

	public function getCountComment()
	{
		return Doctrine_Query::create()->from('Commentaire c')->where("c.content_type = 'idea'")->andWhere("c.content_id = ?", $this->getId())->count();
	}
}
