<?php

/**
 * Ressource
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ressource extends BaseRessource
{
	public function postInsert($values)
	{
		// Create Story
		if($this->get("projet_id"))
			Story::set_relation("Projet", $this->get("projet_id"));
		elseif($this->get("event_id"))
			Story::set_relation("Event", $this->get("event_id"));

		Story::publish(
					"default",
					"Ressource",
					$this->get("id"),
					sfContext::getInstance()->getUser()->getId(),
					"ressource"
		);
	}

	public function getPicture()
	{
		$extension = pathinfo($this->getFichier(),  PATHINFO_EXTENSION);
		$type = "";

		switch($extension)
		{
			case "pdf":
				$type = "Pdf";
			break;
			case "doc":
				$type = "Word";
			break;
			case "docx":
				$type = "Word";
			break;
			case "ppt":
				$type = "PowerPoint";
			break;
			case "xls":
				$type = "Excel";
			break;
			default:
				$type = "Word";
			break;
		}

		return array($type, $type. "_Icon_PNG.png");
	}
}
