<?php

/**
 * RessourceFiliereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RessourceFiliereTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RessourceFiliereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RessourceFiliere');
    }
}