<?php

/**
 * RessourceThemeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RessourceThemeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RessourceThemeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RessourceTheme');
    }
}