<?php

/**
 * SegmentMetierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SegmentMetierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SegmentMetierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SegmentMetier');
    }
}