<?php

/**
 * SegmentCompetenceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SegmentCompetenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SegmentCompetenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SegmentCompetence');
    }
}