<?php

/**
 * SegmentFiliereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SegmentFiliereTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SegmentFiliereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SegmentFiliere');
    }
}