<?php

/**
 * SegmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SegmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SegmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Segment');
    }
}