<?php

/**
 * StatsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Stats');
    }
}