<?php

/**
 * StoryPicturesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoryPicturesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StoryPicturesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StoryPictures');
    }
}