<?php

/**
 * StoryBuddiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoryBuddiesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StoryBuddiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StoryBuddies');
    }
}