<?php

/**
 * StructureCompetenceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StructureCompetenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StructureCompetenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StructureCompetence');
    }
}