<?php

/**
 * StructureThemeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StructureThemeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StructureThemeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StructureTheme');
    }
}