<?php

/**
 * StructureFiliereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StructureFiliereTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StructureFiliereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StructureFiliere');
    }
}