<?php

/**
 * StructureMetierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StructureMetierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StructureMetierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StructureMetier');
    }
}