<?php

/**
 * WishInvitation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rrr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WishInvitation extends BaseWishInvitation
{
	public function postInsert($event)
	{
		$referents = Doctrine_Query::create()
									->from("ProfilProjet")
									->where("role=?", "referent")
									->andWhere("projet_id=?", $this->get("projet_id"))
									->execute();
									
		foreach($referents as $r)
		{
			rMail::create($r->getProfilId(), "", "wishp", array("gname" => $r->getProjet()->getNom(), "uname" => sfContext::getInstance()->getUser()->getObject()->__toString()), true)
					->send();
		}
	}
}
