<?php

/**
 * WishInvitationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WishInvitationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WishInvitationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WishInvitation');
    }
}