generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Commune
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          commune
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   Liste des communes
        display: [nom, code_postal]
      filter:
        display: [code_postal, nom, code_insee]
      form:    ~
      edit:    ~
      new:     ~
