generator:
  class: sfDoctrineGenerator
  param:
    model_class:           HomeNews
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          home_news
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:         Liste des mise en avant d'accueil
        display: [titre, titre_lien]
      filter:
        display: [titre, titre_lien]
      form:    ~
      edit:    ~
      new:     ~
