generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Competence
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          competence
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=nom, is_activated]
      filter:
        display: [nom, is_activated]
      form:    ~
      edit:    ~
      new:     ~

