generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Structure
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          structure
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:         Liste des structures
        display: [Nom, Ville]
      filter:
        display: [nom, ville, code_postal]
      form:    ~
      edit:    ~
      new:     ~
